from django.db import models

class RegistroViolencia(models.Model):
    NU_ANO = models.IntegerField( null=True, blank=True)
    DT_NOTIFIC = models.DateField(max_length=50, null=True, blank=True)
    MUNICIPIO = models.CharField(max_length=50, null=True, blank=True)
    DT_OCOR = models.DateField(max_length=50, null=True, blank=True)
    DT_NASC = models.CharField(max_length=50, null=True, blank=True)
    CS_SEXO = models.CharField(max_length=50, null=True, blank=True)
    CS_RACA = models.CharField(max_length=50, null=True, blank=True)
    MUNIC_RESI = models.CharField(max_length=50, null=True, blank=True)
    MN_OCOR = models.CharField(max_length=50, null=True, blank=True)
    LOCAL_OCOR = models.CharField(max_length=50, null=True, blank=True)
    LOCAL_ESPEC = models.CharField(max_length=50, null=True, blank=True)
    OUT_VEZES = models.CharField(max_length=50, null=True, blank=True)
    AG_FORCA = models.CharField(max_length=50, null=True, blank=True)
    AG_ENFOR = models.CharField(max_length=50, null=True, blank=True)
    AG_OBJETO = models.CharField(max_length=50, null=True, blank=True)
    AG_CORTE = models.CharField(max_length=50, null=True, blank=True)
    AG_QUENTE = models.CharField(max_length=50, null=True, blank=True)
    AG_ENVEN = models.CharField(max_length=50, null=True, blank=True)
    AG_FOGO = models.CharField(max_length=50, null=True, blank=True)
    AG_AMEACA = models.CharField(max_length=50, null=True, blank=True)
    AG_OUTROS = models.CharField(max_length=50, null=True, blank=True)
    AG_ESPEC = models.CharField(max_length=50, null=True, blank=True)
    SEX_ASSEDI = models.CharField(max_length=50, null=True, blank=True)
    SEX_ESTUPR = models.CharField(max_length=50, null=True, blank=True)
    REL_PAI = models.CharField(max_length=50, null=True, blank=True)
    REL_MAE = models.CharField(max_length=50, null=True, blank=True)
    REL_PAD = models.CharField(max_length=50, null=True, blank=True)
    REL_MA = models.CharField(max_length=50, null=True, blank=True)
    REL_CONJ = models.CharField(max_length=50, null=True, blank=True)
    REL_EXCON = models.CharField(max_length=50, null=True, blank=True)
    REL_NAMO = models.CharField(max_length=50, null=True, blank=True)
    REL_EXNAM = models.CharField(max_length=50, null=True, blank=True)
    REL_FILHO = models.CharField(max_length=50, null=True, blank=True)
    REL_IRMAO = models.CharField(max_length=50, null=True, blank=True)
    REL_CONHEC = models.CharField(max_length=50, null=True, blank=True)
    REL_DESCO = models.CharField(max_length=50, null=True, blank=True)
    REL_CUIDA = models.CharField(max_length=50, null=True, blank=True)
    REL_PATRAO = models.CharField(max_length=50, null=True, blank=True)
    REL_INST = models.CharField(max_length=50, null=True, blank=True)
    REL_POL = models.CharField(max_length=50, null=True, blank=True)
    REL_PROPRI = models.CharField(max_length=50, null=True, blank=True)
    REL_OUTROS = models.CharField(max_length=50, null=True, blank=True)
    REL_ESPEC = models.CharField(max_length=50, null=True, blank=True)
    AUTOR_SEXO = models.CharField(max_length=50, null=True, blank=True)
    ENC_SAUDE = models.CharField(max_length=50, null=True, blank=True)
    ASSIST_SOC = models.CharField(max_length=50, null=True, blank=True)
    REDE_EDUCA = models.CharField(max_length=50, null=True, blank=True)
    ATEND_MULH = models.CharField(max_length=50, null=True, blank=True)
    CONS_TUTEL = models.CharField(max_length=50, null=True, blank=True)
    CONS_IDO = models.CharField(max_length=50, null=True, blank=True)
    DELEG_IDOS = models.CharField(max_length=50, null=True, blank=True)
    DIR_HUMAN = models.CharField(max_length=50, null=True, blank=True)
    MPU = models.CharField(max_length=50, null=True, blank=True)


    def __str__(self):
        return f"{self.tipo_crime} em {self.uf} ({self.ano}) - {self.ocorrencias} casos"

    class Meta:
        verbose_name = "Registro de Violência"
        verbose_name_plural = "Registros de Violência"
