# Generated by Django 5.2.2 on 2025-07-08 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_gerenciadas', to=settings.AUTH_USER_MODEL)),
                ('profissionais', models.ManyToManyField(blank=True, related_name='equipes_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
