# Generated by Django 5.2.2 on 2025-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NU_ANO', models.IntegerField(blank=True, null=True)),
                ('DT_NOTIFIC', models.DateField(blank=True, max_length=50, null=True)),
                ('MUNICIPIO', models.CharField(blank=True, max_length=50, null=True)),
                ('DT_OCOR', models.DateField(blank=True, max_length=50, null=True)),
                ('DT_NASC', models.CharField(blank=True, max_length=50, null=True)),
                ('CS_SEXO', models.CharField(blank=True, max_length=50, null=True)),
                ('CS_RACA', models.CharField(blank=True, max_length=50, null=True)),
                ('MUNIC_RESI', models.CharField(blank=True, max_length=50, null=True)),
                ('MN_OCOR', models.CharField(blank=True, max_length=50, null=True)),
                ('LOCAL_OCOR', models.CharField(blank=True, max_length=50, null=True)),
                ('LOCAL_ESPEC', models.CharField(blank=True, max_length=50, null=True)),
                ('OUT_VEZES', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_FORCA', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_ENFOR', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_OBJETO', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_CORTE', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_QUENTE', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_ENVEN', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_FOGO', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_AMEACA', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_OUTROS', models.CharField(blank=True, max_length=50, null=True)),
                ('AG_ESPEC', models.CharField(blank=True, max_length=50, null=True)),
                ('SEX_ASSEDI', models.CharField(blank=True, max_length=50, null=True)),
                ('SEX_ESTUPR', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_PAI', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_MAE', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_PAD', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_MA', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_CONJ', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_EXCON', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_NAMO', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_EXNAM', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_FILHO', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_IRMAO', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_CONHEC', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_DESCO', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_CUIDA', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_PATRAO', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_INST', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_POL', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_PROPRI', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_OUTROS', models.CharField(blank=True, max_length=50, null=True)),
                ('REL_ESPEC', models.CharField(blank=True, max_length=50, null=True)),
                ('AUTOR_SEXO', models.CharField(blank=True, max_length=50, null=True)),
                ('ENC_SAUDE', models.CharField(blank=True, max_length=50, null=True)),
                ('ASSIST_SOC', models.CharField(blank=True, max_length=50, null=True)),
                ('REDE_EDUCA', models.CharField(blank=True, max_length=50, null=True)),
                ('ATEND_MULH', models.CharField(blank=True, max_length=50, null=True)),
                ('CONS_TUTEL', models.CharField(blank=True, max_length=50, null=True)),
                ('CONS_IDO', models.CharField(blank=True, max_length=50, null=True)),
                ('DELEG_IDOS', models.CharField(blank=True, max_length=50, null=True)),
                ('DIR_HUMAN', models.CharField(blank=True, max_length=50, null=True)),
                ('MPU', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Violência',
                'verbose_name_plural': 'Registros de Violência',
            },
        ),
    ]
