# Generated by Django 5.2.2 on 2025-06-10 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('total_anual_csv', models.FloatField(blank=True, help_text='Total anual somado a partir do CSV', null=True)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='DadosMensaisRegiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(help_text='Ano do registro (ex: 2024)')),
                ('mes', models.IntegerField(help_text='Mês do registro (1 para Janeiro, 12 para Dezembro)')),
                ('valor', models.FloatField(help_text='Valor numérico para o mês/ano')),
                ('regiao', models.ForeignKey(help_text='Região a que o dado se refere', on_delete=django.db.models.deletion.CASCADE, to='dashboard.regiao')),
            ],
            options={
                'verbose_name': 'Dado Mensal da Região',
                'verbose_name_plural': 'Dados Mensais das Regiões',
                'ordering': ['regiao', 'ano', 'mes'],
                'unique_together': {('regiao', 'ano', 'mes')},
            },
        ),
    ]
