# Generated by Django 5.2.2 on 2025-07-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroViolencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('tipo_crime', models.CharField(max_length=255)),
                ('ocorrencias', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Registro de Violência',
                'verbose_name_plural': 'Registros de Violência',
            },
        ),
        migrations.DeleteModel(
            name='DadosMensaisRegiao',
        ),
        migrations.DeleteModel(
            name='Regiao',
        ),
    ]
